{
 "title": "QNAP 總部 4 樓高峰用電狀況 - 2",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "4F-3",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "content": "<style>\n#panel-29 .panel-title-text{\nfont-size: 50px;\n}\n#panel-29 .panel-container {\nheight: 100%;\n}\n.panel-title-text{\nfont-size: 15px;\n}\n.panel-container {\nheight: 100%;\n}\n\n</style>"
  },
  {
   "title": "4F-4",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<style>\n#panel-30 .panel-title-text{\nfont-size: 50px;\n}\n#panel-30 .panel-container {\nheight: 100%;\n}\n\n</style>"
  },
  {
   "title": "4F-5",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "<style>\n#panel-31 .panel-title-text{\nfont-size: 50px;\n}\n#panel-31 .panel-container {\nheight: 100%;\n}\n\n</style>"
  },
  {
   "title": "超約狀態",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "CC_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-3" }
     ]
    }
   ]
  },
  {
   "title": "超約狀態",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "CC_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-4" }
     ]
    }
   ]
  },
  {
   "title": "超約狀態",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "CC_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-5" }
     ]
    }
   ]
  },
  {
   "title": "超約附加費用",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "exceed_fee" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-3" }
     ]
    }
   ]
  },
  {
   "title": "超約附加費用",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "exceed_fee" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-4" }
     ]
    }
   ]
  },
  {
   "title": "超約附加費用",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "exceed_fee" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-5" }
     ]
    }
   ]
  },
  { "title": "總部 4F-3 ~ 4F-5 狀態改變紀錄", "type": "alertlist", "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 } },
  {
   "title": "總部 4F-3 ~ 4F-5 各樓層本月超約次數統計",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_floor]]",
     "groupBy": [
      { "params": [ "floor" ], "type": "tag" }
     ],
     "measurement": "EST_FEE",
     "select": [
      [
       { "params": [ "P_exceed_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-3" },
      { "condition": "OR", "key": "floor", "operator": "=", "value": "4F-4" },
      { "condition": "OR", "key": "floor", "operator": "=", "value": "4F-5" }
     ]
    }
   ]
  },
  {
   "title": "4F-3 每 15 分鐘平均用電功率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "4F-3",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EM_Records",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "4F-3" }
     ]
    }
   ]
  },
  {
   "title": "4F-4 每 15 分鐘平均用電功率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "4F-4",
     "measurement": "p_mean_15m",
     "select": [
      [
       { "params": [ "P" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-4" }
     ]
    }
   ]
  },
  {
   "title": "4F-5 每 15 分鐘平均用電功率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "4F-5",
     "measurement": "p_mean_15m",
     "select": [
      [
       { "params": [ "P" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "floor", "operator": "=", "value": "4F-5" }
     ]
    }
   ]
  }
 ]
}