{
 "title": "QNAP 總部用電狀態",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<script>\nfunction refreshMyPanel() {\n  var now = new Date();  // the current datetime as a Date object\n  // var utc = now.getTime() + (now.getTimezoneOffset() * 60000);\n  // var nowwithtimezone = new Date(utc + (3600000*8));\n  \n  var start = new Date(Date.UTC(\n      now.getFullYear(), \n      now.getMonth(),\n      1 , 0, 0, 0, 0)).toISOString();\n      \n  var end = new Date(Date.UTC(\n      now.getFullYear(), \n      now.getMonth() + 1,\n      0 , 0, 0, 0, 0)).toISOString();\n      \n  start = start.split(\"T\")[0];\n  end = end.split(\"T\")[0];\n  \n  datetext = now.toTimeString().split(' ')[0]\n    \n  document.getElementById(\"interval\").innerHTML = `本期區間: ${start} ~ ${end} 目前時間: ${formatDate(now) + \" \" + datetext}`;\n}\n\n$(document).ready(function() {\n  refreshMyPanel(); // For the initial load of data\n\n  // Refetch data every time the \"refresh\" event is broadcast\n  angular.element('#panel-10').injector().get('$rootScope').$on('refresh', function() {\n    refreshMyPanel();\n  });\n});\n\nfunction formatDate(date) {\n  var d = new Date(date),\n      month = '' + (d.getMonth() + 1),\n      day = '' + d.getDate(),\n      year = d.getFullYear();\n  \n  if (month.length < 2) month = '0' + month;\n  if (day.length < 2) day = '0' + day;\n  \n  return [year, month, day].join('-');\n}\n\n</script>\n\n\n<font size=5><center id=\"interval\"></center></font>\n<style>\n.panel-title-text{\nfont-size: 15px;\n}\n.panel-container {\nheight: 100%;\n}\n</style>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from (select last(EP_Diff) from EST_FEE WHERE $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from (select last(total_fee_after_tax) from EST_FEE WHERE $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "QNAP 總部目前超約狀態", "type": "alertlist", "gridPos": { "h": 22, "w": 4, "x": 0, "y": 5 } },
  {
   "title": "總部各樓層本月用電比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 5 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "2樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(EP_Diff) from EST_FEE where \"floor\" =~ /^2/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "2F" }
     ]
    },
    {
     "alias": "3樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(EP_Diff) from EST_FEE where \"floor\" =~ /^3/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "3F" }
     ]
    },
    {
     "alias": "4樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(EP_Diff) from EST_FEE where \"floor\" =~ /^4/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "4F" }
     ]
    },
    {
     "alias": "5樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(EP_Diff) from EST_FEE where \"floor\" =~ /^5/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "5F" }
     ]
    }
   ]
  },
  {
   "title": "總部各樓層本月電費比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 5 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "2樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(total_fee_after_tax) from EST_FEE where \"floor\" =~ /^2/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "2F" }
     ]
    },
    {
     "alias": "3樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(total_fee_after_tax) from EST_FEE where \"floor\" =~ /^3/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "3F" }
     ]
    },
    {
     "alias": "4樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(total_fee_after_tax) from EST_FEE where \"floor\" =~ /^4/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "4F" }
     ]
    },
    {
     "alias": "5樓",
     "measurement": "FLOOR_FEE",
     "query": "select sum(*) from (select last(total_fee_after_tax) from EST_FEE where \"floor\" =~ /^5/ AND $timeFilter group by \"floor\")",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "5F" }
     ]
    }
   ]
  },
  {
   "title": "QNAP 總部本月超約狀態",
   "type": "table",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "floor" ], "type": "tag" }
     ],
     "measurement": "EST_FEE",
     "query": "SELECT last(\"CC_status\"), last(\"CC_exceed_ratio\"), last(\"CC\"), last(\"P_max\"), last(\"exceed_fee\") FROM \"EST_FEE\" WHERE (\"CC_status\" != -1) AND $timeFilter GROUP BY \"floor\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "CC_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "CC_exceed_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "CC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "P_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "exceed_fee" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "CC_status", "operator": "!=", "value": "-1" }
     ]
    }
   ]
  },
  {
   "title": "總部各戶本月用電比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_floor]]",
     "groupBy": [
      { "params": [ "floor" ], "type": "tag" }
     ],
     "measurement": "EST_FEE",
     "query": "SELECT last(\"EP_Diff\") FROM \"EST_FEE\" WHERE $timeFilter GROUP BY \"floor\"",
     "select": [
      [
       { "params": [ "EP_Diff" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "總部各戶本月電費比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_floor]]",
     "groupBy": [
      { "params": [ "floor" ], "type": "tag" }
     ],
     "measurement": "EST_FEE",
     "query": "SELECT last(\"total_fee_after_tax\") FROM \"EST_FEE\" WHERE $timeFilter GROUP BY \"floor\"",
     "select": [
      [
       { "params": [ "total_fee_after_tax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}